services:
  web:
    build: .
    container_name: udata_auction_app
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - public_env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/auction_db
    command: ["sh", "-c", "alembic upgrade head && uvicorn src.app.main:app --host 0.0.0.0 --port 8000"]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: udata_auction_db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auction_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auction_db"]
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  db-data:
